### ISSUE TITLE
drawing example doesn't draw anything

### ISSUE THREAD

**Issue by mifopen** [ryleelyman/zig-cocoa-examples#1]
First of all, HUGE thanks to you for compiling this together. I'm new to Zig, Objective-C and macOS programming, so it is very helpful 🔥.

The only issue I've encountered is with the `drawing` example. It just opens an empty window for me. Could you please confirm that it works on your side so that I try to find a problem with my setup?

**Comment by robbielyman** [comment]
thanks for your kind words! i've attached a working-as-intended screenshot of the drawing window; it should be empty, but green.

<img width="368" alt="Screenshot 2023-10-25 at 8 21 31 AM" src="https://github.com/ryleelyman/zig-cocoa-examples/assets/46907231/94cc30f5-655b-4d22-9e2c-a489b123416c">

**Comment by mifopen** [comment]
Yeah, I expect something like this, but 
![image](https://github.com/ryleelyman/zig-cocoa-examples/assets/19679857/9f28ce56-e53f-4831-976d-65c550980e46)
OK, will try to figure out what's wrong. Thanks for your reply!
